name: bank_ghavanin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  pin_code_fields: ^7.4.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_typeahead: ^3.2.0
  floor: ^1.3.0
  mockito: ^5.2.0
  bloc_test: ^9.0.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: YekanBold
      fonts:
        - asset: assets/fonts/YEKAN BAKH BOLD.TTF
    - family: YekanLight
      fonts:
        - asset: assets/fonts/YEKAN BAKH MEDIUM.TTF